training_pipeline_config:
  pipeline_name: src
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_url: https://github.com/devarajvsnd/InsuranceData/raw/main/insurance_claims.tgz
  raw_data_dir: raw_data
  tgz_download_dir: tgz_data
  ingested_dir: ingested_data


data_validation_config:
  schema_dir: config
  schema_file_name: schema.json
  report_file_name: report.json
  report_page_file_name: report.html


data_transformation_config:
  
  transformed_dir: transformed_data
  cluster_dir: cluster_model
  


  
model_trainer_config:
  trained_model_dir: trained_model
  model_file_name: model.pkl
  base_accuracy: 0.6
  model_config_dir: config
  model_config_file_name: model.yaml





model_evaluation_config:
  model_evaluation_file_name: model_evaluation.yaml
  

model_pusher_config:
  model_export_dir: saved_models
