grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 3

model_selection:
  
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      n_estimators: [100, 130]
      criterion: ['gini', 'entropy']
      max_depth: range(8, 10, 1)
      n_jobs: -1
    


  module_1:
    class: SVC
    module: sklearn.svm
    params:
      kernel: ['rbf', 'sigmoid']
      C: [0.1, 0.5, 1.0]
      random_state: [0, 100, 200, 300]
     
    
