
NumberofColumns : 39,
ColName: 
  months_as_customer : Integer,
  age: Integer,
  policy_number: Integer,
  policy_bind_date: varchar,
  policy_state: varchar,
  policy_csl: varchar,
  policy_deductable: Integer,
  policy_annual_premium: Integer,
  umbrella_limit: Integer,
  insured_zip: Integer,
  insured_sex: varchar,
  insured_education_level: varchar,
  insured_occupation: varchar,
  insured_hobbies: varchar,
  insured_relationship: varchar,
  capital-gains: Integer,
  capital-loss: Integer,
  incident_date: varchar,
  incident_type: varchar,
  collision_type: varchar,
  incident_severity: varchar,
  authorities_contacted: varchar,
  incident_state: varchar,
  incident_city: varchar,
  incident_location: varchar,
  incident_hour_of_the_day: Integer,
  number_of_vehicles_involved: Integer,
  property_damage: varchar,
  bodily_injuries: Integer,
  witnesses: Integer,
  police_report_available: varchar,
  total_claim_amount: Integer,
  injury_claim: Integer,
  property_claim: Integer,
  vehicle_claim: Integer,
  auto_make: varchar,
  auto_model: varchar,
  auto_year: Integer,
  fraud_reported: varchar


numerical_columns:
  - months_as_customer
  - age
  - policy_number
  - policy_deductable
  - policy_annual_premium
  - umbrella_limit
  - insured_zip
  - capital-gains
  - capital-loss
  - incident_hour_of_the_day
  - number_of_vehicles_involved
  - bodily_injuries
  - bodily_injuries
  - witnesses
  - total_claim_amount
  - injury_claim
  - property_claim
  - vehicle_claim
  - auto_year


categorical_columns:

  - policy_bind_date
  - policy_state
  - policy_csl
  - insured_sex
  - insured_education_level
  - insured_occupation
  - insured_hobbies
  - insured_relationship
  - incident_date
  - incident_type
  - collision_type
  - incident_severity
  - authorities_contacted
  - incident_state
  - incident_city
  - incident_location
  - property_damage
  - police_report_available
  - auto_make
  - auto_model
  - fraud_reported

target_column: fraud_reported